import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { Roboto_Mono } from "next/font/google";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Toaster } from "sonner";
import Footer from "@/components/Footer";

const mono = Roboto_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Cloning Jira",
    description: "Generated by create next app",
};
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider
            appearance={{
                baseTheme: dark,
                variables: {
                    colorPrimary: "#3b82f6",
                    colorBackground: "#1a202c",
                    colorInputBackground: "#2d3748",
                    colorInputText: "#f3f4f6",
                },
                elements: {
                    formButtonPrimary:
                        "bg-gray-300 hover:bg-gray-500 border-white",
                    card: "bg-gray-800",
                },
            }}
        >
            <html lang="en">
                <body
                    className={`${mono.className} animated-dotted-background`}
                >
                    <ThemeProvider attribute="class" defaultTheme="dark">
                        {/* Header */}
                        <Header />
                        <main className="min-h-screen">{children}</main>
                        <Toaster richColors />
                        {/* Footer */}
                        <Footer />
                    </ThemeProvider>
                </body>
            </html>
        </ClerkProvider>
    );
}
