name: CI/CD Pipeline for Next.js

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    # Build job
    build:
        runs-on: self-hosted
        steps:
            # Step 1: Check out the code
            - name: Checkout code
              uses: actions/checkout@v3

            # Step 2: Set up Node.js
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20"

            # Step 3: Install dependencies
            - name: Install dependencies
              run: npm install --legacy-peer-deps

            # Step 4: Build the Next.js project
            - name: Build project
              run: npm run build

    # Deploy job
    deploy:
        runs-on: self-hosted
        needs: build
        steps:
            # Step 1: Set up SSH key
            - name: Set up SSH key
              run: |
                  echo "$SSH_PRIVATE_KEY" > private_key.pem
                  chmod 400 private_key.pem

            # Step 2: Transfer the entire project to the server, excluding node_modules
            - name: Transfer project to the server
              run: |
                  rsync -av --exclude "node_modules" --exclude "*.log" -e "ssh -i private_key.pem" ./ ubuntu@$INSTANCE_IP:/home/ubuntu/jira-clone/

            # Step 3: Deploy and start the application on the server
            - name: Deploy application
              run: |
                  ssh -i private_key.pem ubuntu@$INSTANCE_IP << 'EOF'
                    set -e

                    # Go to the deployment directory
                    cd /home/ubuntu/jira-clone

                    # Start the app using PM2
                    npm run serve:pm2

                    # Restart Nginx
                    sudo systemctl restart nginx
                  EOF

            # Step 4: Clean up the SSH key
            - name: Remove SSH key
              run: rm private_key.pem

        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            INSTANCE_IP: ${{ secrets.INSTANCE_IP }}
