name: CI/CD Pipeline for Next.js

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    # Build job
    build:
        runs-on: self-hosted
        steps:
            # Step 1: Check out the code
            - name: Checkout code
              uses: actions/checkout@v3

            # Step 2: Set up Node.js
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20"

            # Step 3: Install dependencies
            - name: Install dependencies
              run: npm install --legacy-peer-deps

            # Step 4: Build the Next.js project
            - name: Build project
              run: npm run build

            # Step 5: Archive the build files
            - name: Archive build files
              run: tar -czf build.tar.gz .next public package.json package-lock.json

            # Save the artifact for the deploy job
            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                  name: build-files
                  path: build.tar.gz

    # Deploy job
    deploy:
        runs-on: self-hosted
        needs: build
        steps:
            # Step 1: Download the artifact
            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                  name: build-files

            # Step 2: Set up SSH key
            - name: Set up SSH key
              run: |
                  echo "$SSH_PRIVATE_KEY" > private_key.pem
                  chmod 400 private_key.pem

            # Step 3: Transfer project to server
            - name: Transfer project to server
              run: |
                  scp -i private_key.pem build.tar.gz ubuntu@$INSTANCE_IP:/home/ubuntu/jira-clone.tar.gz

            # Step 4: Deploy and start application on server
            - name: Deploy application
              run: |
                  ssh -i private_key.pem ubuntu@$INSTANCE_IP << 'EOF'
                    set -e

                    # Go to the deployment directory
                    cd /home/ubuntu

                    # Clean previous builds
                    rm -rf jira-clone
                    mkdir jira-clone

                    # Extract new build
                    tar -xzf jira-clone.tar.gz -C jira-clone
                    rm jira-clone.tar.gz

                    # Install dependencies and start app
                    cd jira-clone
                    npm install --production --legacy-peer-deps
                    npm run serve:pm2

                    # Restart Nginx
                    sudo systemctl restart nginx
                  EOF

            # Step 5: Clean up the SSH key
            - name: Remove SSH key
              run: rm private_key.pem

        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            INSTANCE_IP: ${{ secrets.INSTANCE_IP }}
